### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by swmonkey** [OrdnanceSurvey/os-api-branding#2]
[README.md](https://github.com/OrdnanceSurvey/os-api-branding#readme) states the contents of this repository are licensed under the [Open Government Licence 3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/) however there is no license for the code.

When using the image/text, can I confirm whether there is a license and attribution required?

**Comment by tmnnrs** [comment]
Hi @swmonkey. You can view the [Open Government Licence 3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/) using the provided link. You can also just include the CDN tags in the header section of your HTML document to add the official OS logo and attribution to your map `<div>` without any further licencing or attribution.
